version: '3.6'
  
services:
  db:
    restart: always
    image: postgres
    container_name: bojnordlug_db
    volumes: 
      - type: volume
        source: bojnord_lug_db
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=blpaygahhbs
      - POSTGRES_USER=blkrbr
      - POSTGRES_PASSWORD=C6McpCsgMcYKeLt

  web:
    build: .
    restart: always
    image: bojnordlug:1.0.0
    container_name: bojnordlug_web
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - VIRTUAL_HOST=bojnordlug.ir
    volumes: 
      - type: volume
        source: bojnord_lug_web
        target: /usr/src/app/public

    ports:
      - "8000"
    depends_on:
      - db

volumes:
  bojnord_lug_web:
  bojnord_lug_db:
  
networks:
        default:
                external:
                        name: internal_net
